 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/transaction_categories", type: :request do
  
  # TransactionCategory. As you add validations to TransactionCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    transaction_category = TransactionCategory.create(name: "some name")
    expect(transaction_category.valid?).to eq(true)
  }

  let(:invalid_attributes) {
  }

  describe "GET /index" do
    it "renders a successful response" do
      TransactionCategory.create! valid_attributes
      get transaction_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      transaction_category = TransactionCategory.create! valid_attributes
      get transaction_category_url(transaction_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_transaction_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      transaction_category = TransactionCategory.create! valid_attributes
      get edit_transaction_category_url(transaction_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TransactionCategory" do
        expect {
          post transaction_categories_url, params: { transaction_category: valid_attributes }
        }.to change(TransactionCategory, :count).by(1)
      end

      it "redirects to the created transaction_category" do
        post transaction_categories_url, params: { transaction_category: valid_attributes }
        expect(response).to redirect_to(transaction_category_url(TransactionCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TransactionCategory" do
        expect {
          post transaction_categories_url, params: { transaction_category: invalid_attributes }
        }.to change(TransactionCategory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post transaction_categories_url, params: { transaction_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transaction_category" do
        transaction_category = TransactionCategory.create! valid_attributes
        patch transaction_category_url(transaction_category), params: { transaction_category: new_attributes }
        transaction_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the transaction_category" do
        transaction_category = TransactionCategory.create! valid_attributes
        patch transaction_category_url(transaction_category), params: { transaction_category: new_attributes }
        transaction_category.reload
        expect(response).to redirect_to(transaction_category_url(transaction_category))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        transaction_category = TransactionCategory.create! valid_attributes
        patch transaction_category_url(transaction_category), params: { transaction_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested transaction_category" do
      transaction_category = TransactionCategory.create! valid_attributes
      expect {
        delete transaction_category_url(transaction_category)
      }.to change(TransactionCategory, :count).by(-1)
    end

    it "redirects to the transaction_categories list" do
      transaction_category = TransactionCategory.create! valid_attributes
      delete transaction_category_url(transaction_category)
      expect(response).to redirect_to(transaction_categories_url)
    end
  end
end
